server:
  port: 80
  # For removing the whitelabel error page
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    path: /error
security:
  basic:
    enabled: false
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false # to prevent exception while serializing empty objects.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iti_admission
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        jdbc:
          batch_size: 100
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

authToken: aa9630752a305d95bb14cd8982506d628420eae9218da47f7e8e967d69ae5778
